# Generated by Django 4.1.5 on 2023-02-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50)),
                ('post_content', models.CharField(max_length=1000)),
                ('publication_date', models.DateField(verbose_name='date of publication')),
            ],
        ),
    ]
