# Generated by Django 4.1.5 on 2023-02-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block0', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(verbose_name='date of publication'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=20)),
                ('comment_content', models.CharField(max_length=250)),
                ('publication_date', models.DateTimeField(verbose_name='date of publication')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block0.post')),
            ],
        ),
    ]
