# Generated by Django 4.1.5 on 2023-04-08 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block0', '0004_remove_comment_comment_author_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 27, 22, 593874, tzinfo=datetime.timezone.utc), verbose_name='date of publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 16, 27, 22, 593472, tzinfo=datetime.timezone.utc), verbose_name='date of publication'),
        ),
    ]
