# Generated by Django 4.2 on 2023-04-17 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block0', '0005_rename_comment_content_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 14, 28, 55, 968698, tzinfo=datetime.timezone.utc), verbose_name='date of publication'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 14, 28, 55, 968698, tzinfo=datetime.timezone.utc), verbose_name='date of publication'),
        ),
    ]
